"""First Migration

Revision ID: 43591b944f10
Revises: 
Create Date: 2025-03-15 22:28:22.935587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43591b944f10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('screening',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screen_number', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seat_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=False),
    sa.Column('availability', sa.Enum('AVAILABLE', 'RESERVED', 'BOOKED', 'ACCESSIBLE_AVAILABLE', 'ACCESSIBLE_RESERVED', 'ACCESSIBLE_BOOKED', 'UNAVAILABLE', name='seatstatus'), nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_accessible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['screening_id'], ['screening.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('showtime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['screening_id'], ['screening.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('showtime')
    op.drop_table('seat_booking')
    op.drop_table('screening')
    op.drop_table('movie')
    # ### end Alembic commands ###
